name: Deploy to Multi-Region EKS Clusters

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region:
          - eu-west-1
          - us-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials manually
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ matrix.region }}
        run: |
          echo "AWS credentials and region set."


      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.111.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Set up kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ matrix.region }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS Cluster
        run: |
          kubectl apply -f kubernetes/

      - name: Verify Deployment
        run: |
          kubectl get pods -n olumoko-voting-app

    environment: ${{ matrix.region }}
